server:
  port: 8040

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway服务自动找到注册到nacos的其他微服务
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center # nacos上的服务名
          predicates:
            # eg. 访问http://localhost:8040/users/* -转发到> user-center/users/*
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/shares/** #或者/admin/**也是可以的
  zipkin:
    base-url: http://localhost:9411/
    # 让nacos不会把上面的url当做服务名称
    discoveryClientEnabled: false
    sleuth:
      # 抽样率 默认0.1（10%）
      sampler:
        # 全部监控数据上报数据库（生产不建议1.0）
        probability: 1.0

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  # 显示健康详情
  endpoint:
    health:
      show-details: always